# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fi8h49avlfsKmx660wnO1J5szAt3X3s+gwmtN2Jfu+A7idff9x5syWDPus8koMqSzf1qzKzsr3zJlh8V7ffL6UdW0yB472B6iKS5S8xB2269MeWdQfA+svwvJN7Hdcsibm9p39yYe9Ze07uZGLtSoZmuG6YPyoaUw6ETxb7TOcVwq5EcArwRRZ0SQk3P0Z4njylpYpaQeRHoIfjmnp/lvjuVFeV3tvFPOmgDlLObmHocNDkxiP2UOJPivNOuFVAzL2OQWSZU9M5/49A6m5tQcvCYcK4E1TOQNiWXQHMFr6yALXJoVWLsNL+p8rbU+FspaSi3FYurHLr5xQ21YhUDBMGJs8SGeMjiy7lCIH6f7c4xN++OhSRTWX5hRUwEgfJQqHw/ixojRl2XQBPI7ZHgrYrVH4qsObc21j61P5ItD9r51ul1LGMfwJ4HzPvvMX38ntomTdAH4Ny6JC6Fr/ijDC5UApzpQA23p9AFADfPGxPh0MW5TLwZ0JvR11Z1M6srpK92RKau5R2ZR4BC/X2ogaLq6b9W+MXUbqI91X2JmDoKgbkj1Qz+CkyqQ/M3pQ36H1fC0bkhZiWybTX4DFwkxSKS6eaVgAQcO0ocKLdTrGvqUtiU30MUjb5ISr7ETkd2yUTYk+5gk8KB647WsPX7IiHv+IOwwMTvmzMgH/cZ9A8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
