travis:
  secure:
    BINSTAR_TOKEN: fi8h49avlfsKmx660wnO1J5szAt3X3s+gwmtN2Jfu+A7idff9x5syWDPus8koMqSzf1qzKzsr3zJlh8V7ffL6UdW0yB472B6iKS5S8xB2269MeWdQfA+svwvJN7Hdcsibm9p39yYe9Ze07uZGLtSoZmuG6YPyoaUw6ETxb7TOcVwq5EcArwRRZ0SQk3P0Z4njylpYpaQeRHoIfjmnp/lvjuVFeV3tvFPOmgDlLObmHocNDkxiP2UOJPivNOuFVAzL2OQWSZU9M5/49A6m5tQcvCYcK4E1TOQNiWXQHMFr6yALXJoVWLsNL+p8rbU+FspaSi3FYurHLr5xQ21YhUDBMGJs8SGeMjiy7lCIH6f7c4xN++OhSRTWX5hRUwEgfJQqHw/ixojRl2XQBPI7ZHgrYrVH4qsObc21j61P5ItD9r51ul1LGMfwJ4HzPvvMX38ntomTdAH4Ny6JC6Fr/ijDC5UApzpQA23p9AFADfPGxPh0MW5TLwZ0JvR11Z1M6srpK92RKau5R2ZR4BC/X2ogaLq6b9W+MXUbqI91X2JmDoKgbkj1Qz+CkyqQ/M3pQ36H1fC0bkhZiWybTX4DFwkxSKS6eaVgAQcO0ocKLdTrGvqUtiU30MUjb5ISr7ETkd2yUTYk+5gk8KB647WsPX7IiHv+IOwwMTvmzMgH/cZ9A8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
