travis:
  secure:
    BINSTAR_TOKEN: Fq07S1dsFz7YX69aeq6vdwBLLyfyACPYM1TKKcnHihimrtAxvFNonABOwf7gm57e204/76iT3JaPuVCtkDptBTsuX0gbx8/pIR6XoQwuGl1Suo49vsr5VNZ9rxOIuCT5jtOsr5sEPdPlqNw8Wg0KFGY+Yr8eulAw73cT0QeU/S0IpKpaRydmD45v8rUu6wfEv5XWPjGOIVPNqHMF/K2L7NBdY6TLLQTyybWl1JYMWYpvLevtEwKFFWmGAsuFiGn0arXe6gOB7EMElbO2teHZLqhDVi1ILonPABCVdCRbq0P9KeA2qLSdgfZ0Gol7ItYqqwIZbiAI2w73M1ivGLnypd8Qh1w7QI2YSZygs6/EtuOz6admUOjMIsIsicsPQKbOU5woRQymNKRZpeljgwNPU4XqUEsfIJSw1RdPKUhxBkfWue6amlywE/JCpIrTAmFPnKV/lO5sz3ltXieGKDiTK8Qk0Xr+Dx7DzN9XMEeZawJBW8o5ML2LOXaYYZoRWlZSNyicNUEnOBCfxLptMyWMvGyEWVHIlI+6pSSLl8MPOgszkSwzRSQpyW5SN8+XUv7TeZDshvcONh+vBACuBGjxUtid6NEK3arMPmH4xh02tVLv/6A2CtzyPJxPqhq8+b+tkYSguhSC9AHY/jlv55bOjoAx94IeJJ9dUDpUFtIiCWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
